### ISSUE TITLE
No fxmanifest.lua

### ISSUE THREAD

**Issue by Riley067** [Mo1810/-LEGACY-mo_parkingMeter#1]
I just tried to add this to my server but there wasn't a manifestfx.lua file for it. I'd love to use it but until there is one added it's unusable at least to someone who isn't the best with coding...

**Comment by Mo1810** [comment]
Hello,
thanks for reaching out to me. 
There should be one in the "mo_parkingMeter" folder.
See >[here](https://github.com/Mo1810/mo_parkingMeter/blob/main/mo_parkingMeter/fxmanifest.lua)<.
